version: "2"

services:
  web:
    build:
      context: .
      dockerfile: web_dockerfile
    volumes:
      - ./..:/var/www/html
    ports:
        - "8000:80"
    links:
        - app

  app:
    build:
      context: .
      dockerfile: app_dockerfile
    volumes:
      - ./..:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./volumes:/var/lib/mysql
      - ./my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=GdS)FP6*B7zJ
      - MYSQL_ROOT_PASSWORD=yQqDx.4(Cnue